services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: brs_prototype_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/brs_prototype_db
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-https://api.openai.com/v1}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-3.5-turbo}
      DEBUG: ${DEBUG:-false}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      VITE_API_BASE: ${VITE_API_BASE:-http://localhost:8000}
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data:
