services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    # volumes:
    #   # Optional: uncomment for development to sync code changes
    #   - ./backend/brs_backend:/app/brs_backend

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "5173:5173"
    restart: always
    # volumes:
    #   # Optional: uncomment for development to sync code changes
    #   - ./frontend/src:/app/src

volumes:
  postgres-data:
